# docker-compose.yml
version: "3.8"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
      - "123:123"
    depends_on:
      - webapp
    networks:
      - internal

  server:
    build:
      context: ./docker/server
    volumes:
      - ./apps/server/:/app
      - ./libs:/app/libs
    command:
      [
        "uvicorn",
        "router:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000"
      ]
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - internal

  customer_bot:
    build:
      context: ./docker/customer_bot
    volumes:
      - .:/app
      - ./libs:/app/libs
      - ./templates:/app/templates
    command: "python apps/customer_bot/bot.py"
    depends_on:
      - server
      - redis
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_URL=http://server:8000
    networks:
      - internal

  kitchen:
    build:
      context: ./docker/kitchen
    volumes:
      - .:/app
      - ./libs:/app/libs
      - ./templates:/app/templates
    command: "python apps/kitchen/bot.py"
    depends_on:
      - server
      - redis
    environment:
      - TELEGRAM_TOKEN=${KITCHEN_BOT_TOKEN}
      - KITCHEN_TG_ID=${KITCHEN_TG_ID}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_URL=http://server:8000
    networks:
      - internal

  webapp:
    build:
      context: ./docker/webapp
    volumes:
      - ./apps/webapp/:/app
      - ./libs:/app/libs
      - ./frontend:/app/frontend
    command:
      [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000"
      ]
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_URL=http://server:8000
    networks:
      - internal

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - internal

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - ./database:/var/lib/postgresql
    networks:
      - internal

  redis:
    image: "redis:alpine"
    container_name: redis
    networks:
      - internal

networks:
  internal:
    driver: bridge
