# docker-compose.yml
version: "3.8"
services:
  server:
    build:
      context: ./apps/server
    volumes:
      - .:/app
    command: ["uvicorn", "apps.server.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8001:8000"
    # networks:
    #   - app-network

    # customer_bot:
    #   build:
    #     context: ./customer_bot
    #   ports:
    #     - "8002:8000"
    #   networks:
    #     - app-network
    #   depends_on:
    #     - server

    # kitchen_bot:
    #   build:
    #     context: ./kitchen_bot
    #   ports:
    #     - "8003:8000"
    #   networks:
    #     - app-network
    #   depends_on:
    #     - server
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql
    # networks:
    #   - app-network

    # networks:
    #   app-network:
    #     driver: bridge
