# docker-compose.yml
version: "3.8"
services:
  server:
    build:
      context: ./docker/server
    volumes:
      - ./apps/server/:/app
      - ./libs:/app/libs
    command:
      [
        "uvicorn",
        "router:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000"
      ]
    ports:
      - "8001:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  customer_bot:
    build:
      context: ./docker/customer_bot
    volumes:
      - .:/app
      - ./libs:/app/libs
      - ./templates:/app/templates
    command: "python apps/customer_bot/bot.py"
    ports:
      - "8002:8000"
    depends_on:
      - server
      - redis
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_URL=http://server:8000

  kitchen:
    build:
      context: ./docker/kitchen
    volumes:
      - .:/app
      - ./libs:/app/libs
      - ./templates:/app/templates
    command: "python apps/kitchen/bot.py"
    ports:
      - "8003:8000"
    depends_on:
      - server
      - redis
    environment:
      - TELEGRAM_TOKEN=${KITCHEN_BOT_TOKEN}
      - KITCHEN_TG_ID=${KITCHEN_TG_ID}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_URL=http://server:8000

  webapp:
    build:
      context: ./docker/webapp
    volumes:
      - ./apps/webapp/:/app
      - ./libs:/app/libs
      - ./frontend:/app/frontend
    command:
      [
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000"
      ]
    ports:
      - "8004:8000"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_URL=http://server:8000

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
