"""timeslots

Revision ID: e3d0cc3ea646
Revises: e9c81cea124f
Create Date: 2024-09-26 14:31:37.153231

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "e3d0cc3ea646"
down_revision: Union[str, None] = "e9c81cea124f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "busy_slots",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("timestamp_created", sa.DateTime(), nullable=False),
        sa.Column("timestamp_updated", sa.DateTime(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("busy_slots")
    # ### end Alembic commands ###
